/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar clientes
         * @description Retorna una lista paginada de clientes con filtros opcionales.
         *     El parametro `name` realiza busqueda parcial (LIKE) por firstName o lastName.
         */
        get: operations["listCustomers"];
        put?: never;
        /**
         * Registrar nuevo cliente
         * @description Registra un nuevo cliente en estado ACTIVE.
         *     Valida unicidad de email y documentNumber por documentType.
         */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener cliente por ID */
        get: operations["getCustomerById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar cliente
         * @description Permite actualizar datos y estado de un cliente.
         */
        patch: operations["updateCustomer"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Estado del cliente.
         *     - ACTIVE: Cliente activo
         *     - INACTIVE: Cliente inactivo (puede reactivarse)
         *     - SUSPENDED: Cliente suspendido temporalmente
         *     - BLOCKED: Cliente bloqueado (requiere intervencion manual)
         * @enum {string}
         */
        CustomerStatus: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "BLOCKED";
        /**
         * @description Preferred communication language
         * @enum {string}
         */
        PreferredLanguage: "es" | "en" | "pt";
        /**
         * @description Tipo de documento de identidad
         * @enum {string}
         */
        DocumentType: "RFC" | "CURP" | "INE" | "PASSPORT";
        Customer: {
            /**
             * Format: uuid
             * @description Identificador unico del cliente
             * @example c1d2e3f4-a5b6-7890-cdef-123456789abc
             */
            customerId: string;
            /**
             * @description Nombre del cliente
             * @example Maria
             */
            firstName: string;
            /**
             * @description Apellidos del cliente
             * @example Garcia Lopez
             */
            lastName: string;
            /**
             * Format: email
             * @description Correo electronico (unico)
             * @example maria.garcia@example.com
             */
            email: string;
            /**
             * @description Numero de telefono
             * @example +52-55-1234-5678
             */
            phone?: string | null;
            documentType: components["schemas"]["DocumentType"];
            /**
             * @description Numero de documento (unico por tipo)
             * @example GALM850101ABC
             */
            documentNumber: string;
            status: components["schemas"]["CustomerStatus"];
            address?: components["schemas"]["Address"];
            preferredLanguage?: components["schemas"]["PreferredLanguage"];
            /**
             * Format: date-time
             * @description Fecha de creacion del registro
             * @example 2024-01-05T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Fecha de ultima actualizacion
             * @example 2024-01-05T12:00:00Z
             */
            updatedAt: string;
        };
        Address: {
            /**
             * @description Calle y numero
             * @example Av. Reforma 222, Piso 10
             */
            street?: string;
            /**
             * @description Ciudad
             * @example Ciudad de Mexico
             */
            city?: string;
            /**
             * @description Estado o provincia
             * @example CDMX
             */
            state?: string;
            /**
             * @description Codigo postal
             * @example 06600
             */
            zipCode?: string;
            /**
             * @description Codigo de pais ISO 3166-1 alpha-2
             * @default MX
             * @example MX
             */
            country: string;
        };
        CreateCustomerRequest: {
            /** @description Nombre del cliente */
            firstName: string;
            /** @description Apellidos del cliente */
            lastName: string;
            /**
             * Format: email
             * @description Correo electronico (debe ser unico)
             */
            email: string;
            /** @description Numero de telefono */
            phone?: string;
            documentType: components["schemas"]["DocumentType"];
            /** @description Numero de documento (debe ser unico por tipo) */
            documentNumber: string;
            address?: components["schemas"]["Address"];
            preferredLanguage?: components["schemas"]["PreferredLanguage"];
        };
        UpdateCustomerRequest: {
            /** @description Nombre del cliente */
            firstName?: string;
            /** @description Apellidos del cliente */
            lastName?: string;
            /** @description Numero de telefono */
            phone?: string;
            status?: components["schemas"]["CustomerStatus"];
            address?: components["schemas"]["Address"];
            preferredLanguage?: components["schemas"]["PreferredLanguage"];
        };
        PaginatedCustomerList: {
            content: components["schemas"]["Customer"][];
            /** @example 0 */
            page: number;
            /** @example 20 */
            size: number;
            /**
             * Format: int64
             * @example 150
             */
            totalElements: number;
            /** @example 8 */
            totalPages: number;
        };
        ErrorResponse: {
            /** @example VALIDATION_ERROR */
            error: string;
            /** @example email is required */
            message: string;
            /**
             * Format: date-time
             * @example 2024-01-05T12:00:00Z
             */
            timestamp: string;
            /** @example /api/v1/customers */
            path: string;
            details?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCustomers: {
        parameters: {
            query?: {
                /** @description Filtrar por estado del cliente */
                status?: components["schemas"]["CustomerStatus"];
                /** @description Filtrar por email exacto */
                email?: string;
                /** @description Busqueda parcial por nombre o apellido (case-insensitive) */
                name?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de clientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "content": [
                     *         {
                     *           "customerId": "c1d2e3f4-a5b6-7890-cdef-123456789abc",
                     *           "firstName": "Maria",
                     *           "lastName": "Garcia Lopez",
                     *           "email": "maria.garcia@example.com",
                     *           "phone": "+52-55-1234-5678",
                     *           "documentType": "RFC",
                     *           "documentNumber": "GALM850101ABC",
                     *           "status": "ACTIVE",
                     *           "address": {
                     *             "street": "Av. Reforma 222, Piso 10",
                     *             "city": "Ciudad de Mexico",
                     *             "state": "CDMX",
                     *             "zipCode": "06600",
                     *             "country": "MX"
                     *           },
                     *           "createdAt": "2024-01-05T12:00:00Z",
                     *           "updatedAt": "2024-01-05T12:00:00Z"
                     *         }
                     *       ],
                     *       "page": 0,
                     *       "size": 20,
                     *       "totalElements": 1,
                     *       "totalPages": 1
                     *     }
                     */
                    "application/json": components["schemas"]["PaginatedCustomerList"];
                };
            };
            /** @description Solicitud invalida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "firstName": "Maria",
                 *       "lastName": "Garcia Lopez",
                 *       "email": "maria.garcia@example.com",
                 *       "phone": "+52-55-1234-5678",
                 *       "documentType": "RFC",
                 *       "documentNumber": "GALM850101ABC",
                 *       "address": {
                 *         "street": "Av. Reforma 222, Piso 10",
                 *         "city": "Ciudad de Mexico",
                 *         "state": "CDMX",
                 *         "zipCode": "06600",
                 *         "country": "MX"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["CreateCustomerRequest"];
            };
        };
        responses: {
            /** @description Cliente registrado exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Solicitud invalida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "VALIDATION_ERROR",
                     *       "message": "email is required",
                     *       "timestamp": "2024-01-05T12:00:00Z",
                     *       "path": "/api/v1/customers"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto de unicidad (email o documento duplicado) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "DUPLICATE_RESOURCE",
                     *       "message": "A customer with email maria.garcia@example.com already exists",
                     *       "timestamp": "2024-01-05T12:00:00Z",
                     *       "path": "/api/v1/customers"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCustomerById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID del cliente */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Cliente no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "NOT_FOUND",
                     *       "message": "Customer with ID c1d2e3f4-a5b6-7890-cdef-123456789abc not found",
                     *       "timestamp": "2024-01-05T12:00:00Z",
                     *       "path": "/api/v1/customers/c1d2e3f4-a5b6-7890-cdef-123456789abc"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID del cliente */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "phone": "+52-55-9876-5432",
                 *       "address": {
                 *         "street": "Av. Insurgentes Sur 1500",
                 *         "city": "Ciudad de Mexico",
                 *         "state": "CDMX",
                 *         "zipCode": "03920",
                 *         "country": "MX"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["UpdateCustomerRequest"];
            };
        };
        responses: {
            /** @description Cliente actualizado exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Solicitud invalida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cliente no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transicion de estado no permitida */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "INVALID_STATE_TRANSITION",
                     *       "message": "Cannot transition from BLOCKED to INACTIVE",
                     *       "timestamp": "2024-01-05T12:00:00Z",
                     *       "path": "/api/v1/customers/c1d2e3f4-a5b6-7890-cdef-123456789abc"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
