##############################################################################
# SPEC: Laboratorio Completo — CRC (OpenShift Local) + Manifiestos K8s
# Issue: #34
##############################################################################

metadata:
  name: lab-environment
  type: infra
  issue: 34
  labels: [infra, openshift, crc, kubernetes, devops]
  status: pending
  priority: critical
  depends_on:
    - infra/kafka
    - infra/apicurio
    - infra/threescale
    - infra/activemq
    - infra/postgres

description: >
  Entorno de laboratorio sobre CRC (OpenShift Local). El cluster
  corre localmente con dos namespaces: guidewire-infra para
  infraestructura y guidewire-apps para microservicios. Todo se
  despliega con manifiestos Kubernetes nativos via oc apply.
  Un solo "./deploy-all.sh" levanta todo. "crc stop" lo apaga.

##############################################################################
# CAPA 1: HOST (tu maquina fisica)
##############################################################################

host:
  requirements:
    description: Lo UNICO que necesitas instalar en tu maquina
    packages:
      - name: CRC (OpenShift Local)
        version: "2.x+"
        install: "Descargar desde https://console.redhat.com/openshift/create/local"
      - name: oc CLI
        version: "4.x+"
        install: "eval $(crc oc-env)  # viene incluido con CRC"
    accounts:
      - name: Red Hat Account
        url: https://console.redhat.com
        description: Cuenta gratuita para descargar CRC y el pull secret

  host_resources:
    minimum:
      memory: 16GB
      cpus: 4
      disk: 60GB
    recommended:
      memory: 32GB
      cpus: 8
      disk: 100GB
    description: >
      CRC necesita minimo 9GB RAM para OpenShift base.
      Con el stack Guidewire completo se recomiendan 14GB para CRC
      (--memory 14336), lo cual requiere ~16GB en el host como minimo.

  project_layout:
    description: Estructura de manifiestos en el repositorio
    tree: |
      lab/openshift/
      ├── deploy-all.sh                  # Script de despliegue completo
      ├── namespaces.yml                 # guidewire-infra + guidewire-apps
      ├── operators/
      │   ├── strimzi-subscription.yml   # Operador Strimzi (Kafka)
      │   ├── amq-broker-subscription.yml# Operador AMQ Broker (ActiveMQ)
      │   └── apicurio-subscription.yml  # Operador Apicurio Registry
      ├── infra/
      │   ├── postgres/
      │   │   ├── secret.yml
      │   │   ├── configmap-init-db.yml
      │   │   ├── pvc.yml
      │   │   ├── deployment.yml
      │   │   └── service.yml
      │   ├── kafka/
      │   │   ├── kafka-cluster.yml      # Strimzi Kafka CR
      │   │   └── kafka-topics.yml       # KafkaTopic CRs
      │   ├── activemq/
      │   │   ├── activemq-broker.yml    # ActiveMQArtemis CR
      │   │   └── activemq-addresses.yml # ActiveMQArtemisAddress CRs
      │   ├── apicurio/
      │   │   └── apicurio-registry.yml  # ApicurioRegistry CR
      │   ├── kafdrop/
      │   │   ├── deployment.yml
      │   │   ├── service.yml
      │   │   └── route.yml
      │   └── threescale/
      │       ├── configmap-apicast.yml
      │       ├── deployment.yml
      │       ├── service.yml
      │       └── route.yml
      └── apps/
          ├── billing-service/
          │   ├── buildconfig.yml
          │   ├── deployment.yml
          │   ├── service.yml
          │   └── route.yml
          ├── camel-gateway/
          │   └── ...
          ├── incidents-service/
          │   └── ...
          ├── customers-service/
          │   └── ...
          └── drools-engine/
              └── ...

##############################################################################
# CAPA 2: CRC (OpenShift Local)
##############################################################################

crc:
  version: "2.x+"
  openshift_version: "4.x"

  vm_resources:
    memory: 14336            # 14GB RAM
    cpus: 6
    disk: 60GB
    description: >
      Suficiente para OpenShift base (~4GB) + todo el stack (~6GB)
      + margen para builds y operaciones.

  namespaces:
    - name: guidewire-infra
      description: Infraestructura (PostgreSQL, Kafka, ActiveMQ, Apicurio, Kafdrop, 3Scale)
    - name: guidewire-apps
      description: Microservicios de negocio (Billing, Incidents, Customers, Camel, Drools)

  operators:
    - name: Strimzi
      description: Operador de Kafka para Kubernetes
      channel: strimzi-0.40.x
    - name: AMQ Broker
      description: Operador de ActiveMQ Artemis para OpenShift
      channel: 7.11.x
    - name: Apicurio Registry
      description: Operador de Apicurio Schema Registry
      channel: 2.x

  routes:
    description: >
      OpenShift expone servicios como Routes con TLS automatico.
      Accesibles desde el host via *.apps-crc.testing.
    endpoints:
      - { host: "console-openshift-console.apps-crc.testing", description: "OpenShift Console" }
      - { host: "apicast-guidewire-infra.apps-crc.testing", description: "3Scale API Gateway" }
      - { host: "apicurio-guidewire-infra.apps-crc.testing", description: "Apicurio UI" }
      - { host: "kafdrop-guidewire-infra.apps-crc.testing", description: "Kafdrop UI" }
      - { host: "billing-service-guidewire-apps.apps-crc.testing", description: "Billing Service" }
      - { host: "incidents-service-guidewire-apps.apps-crc.testing", description: "Incidents Service" }
      - { host: "customers-service-guidewire-apps.apps-crc.testing", description: "Customers Service" }
      - { host: "camel-gateway-guidewire-apps.apps-crc.testing", description: "Camel Gateway" }
      - { host: "drools-engine-guidewire-apps.apps-crc.testing", description: "Drools Engine" }

##############################################################################
# CAPA 3: SERVICIOS DESPLEGADOS
##############################################################################

services:
  infrastructure:
    namespace: guidewire-infra
    components:
      postgres:
        type: Deployment
        image: docker.io/postgres:16-alpine
        resources:
          requests: { cpu: 250m, memory: 256Mi }
          limits: { cpu: 500m, memory: 512Mi }
        storage: PVC 5Gi

      kafka:
        type: Strimzi Kafka CR
        replicas: 1
        resources:
          requests: { cpu: 500m, memory: 1Gi }
          limits: { cpu: "1", memory: 2Gi }

      activemq:
        type: ActiveMQArtemis CR
        replicas: 1
        resources:
          requests: { cpu: 250m, memory: 512Mi }
          limits: { cpu: 500m, memory: 1Gi }

      apicurio:
        type: ApicurioRegistry CR
        replicas: 1
        persistence: sql (PostgreSQL)

      kafdrop:
        type: Deployment
        image: docker.io/obsidiandynamics/kafdrop:4.0.1
        resources:
          requests: { cpu: 100m, memory: 256Mi }
          limits: { cpu: 250m, memory: 512Mi }

      threescale:
        type: Deployment
        image: quay.io/3scale/apicast:v3.11
        resources:
          requests: { cpu: 100m, memory: 128Mi }
          limits: { cpu: 250m, memory: 256Mi }

  applications:
    namespace: guidewire-apps
    build_strategy: Binary (oc start-build --from-dir)
    components:
      billing-service:
        build: Source-to-Image (S2I) / Binary
        source: components/billing-service

      camel-gateway:
        build: Source-to-Image (S2I) / Binary
        source: components/camel-gateway

      incidents-service:
        build: Source-to-Image (S2I) / Binary
        source: components/incidents-service

      customers-service:
        build: Source-to-Image (S2I) / Binary
        source: components/customers-service

      drools-engine:
        build: Source-to-Image (S2I) / Binary
        source: components/drools-engine

  startup_order:
    phase_1_operators:
      description: Instalar operadores desde OperatorHub
      components:
        - Strimzi
        - AMQ Broker
        - Apicurio Registry
      wait: CSV status Succeeded

    phase_2_data:
      description: Almacenamiento
      depends_on: phase_1_operators
      components:
        - postgres
      wait: Deployment Available

    phase_3_messaging:
      description: Mensajeria
      depends_on: phase_1_operators
      components:
        - kafka (Strimzi CR)
        - activemq (AMQ Broker CR)
      wait: CR status Ready

    phase_4_platform:
      description: Plataforma y herramientas
      depends_on: [phase_2_data, phase_3_messaging]
      components:
        - apicurio (ApicurioRegistry CR)
        - kafdrop
        - threescale
      wait: pods Ready

    phase_5_apps:
      description: Microservicios de negocio
      depends_on: phase_4_platform
      components:
        - billing-service
        - camel-gateway
        - incidents-service
        - customers-service
        - drools-engine
      wait: pods Ready

  total_resources:
    estimated_memory: 6GB
    estimated_cpu: 4 cores
    description: >
      ~43% de los 14GB asignados a CRC.
      OpenShift base consume ~4GB adicionales.
      Deja ~4GB libres para builds y operaciones.

##############################################################################
# CAPA 4: OPERACIONES DIA A DIA
##############################################################################

operations:
  cluster_lifecycle:
    description: Comandos desde tu HOST

    encender_cluster:
      command: crc start
      description: >
        Primera vez: configura el cluster, instala OpenShift.
        Siguientes veces: enciende la VM donde la dejaste.

    apagar_cluster:
      command: crc stop
      description: >
        Detiene la VM del cluster. Los datos persisten.
        Equivale a apagar un servidor.

    estado:
      command: crc status
      description: >
        Muestra estado del cluster, uso de RAM y disco.

    consola_web:
      command: crc console
      description: >
        Abre la consola web de OpenShift en el navegador.

    destruir_cluster:
      command: crc delete
      description: >
        Elimina la VM del cluster por completo. Borra todo.
        Puedes recrearlo con "crc start".

    limpiar_config:
      command: crc cleanup
      description: >
        Elimina la configuracion de CRC (DNS, libvirt, etc.).
        Ejecutar despues de crc delete para limpieza total.

  stack_operations:
    description: Comandos para gestionar el stack desplegado

    desplegar_todo:
      command: cd lab/openshift && ./deploy-all.sh
      description: Despliega infraestructura + aplicaciones

    desplegar_infra:
      command: ./deploy-all.sh --infra
      description: Solo infraestructura

    desplegar_apps:
      command: ./deploy-all.sh --apps
      description: Solo aplicaciones

    ver_pods:
      command: oc get pods -n guidewire-infra && oc get pods -n guidewire-apps
      description: Ver estado de todos los pods

    ver_logs:
      command: oc logs -f deploy/[servicio] -n [namespace]
      description: Ver logs de un servicio especifico

    shell_en_pod:
      command: oc exec -it deploy/[servicio] -n [namespace] -- bash
      description: Abrir shell interactiva en un pod

    reconstruir_imagen:
      command: oc start-build [servicio] -n guidewire-apps --from-dir=../../components/[servicio] --follow
      description: Reconstruir la imagen de un servicio

    escalar:
      command: oc scale deploy/[servicio] --replicas=N -n [namespace]
      description: Escalar un servicio

    borrar_todo:
      command: oc delete project guidewire-infra guidewire-apps
      description: Eliminar todos los recursos del proyecto

##############################################################################
# RESUMEN: QUE INSTALAS EN TU MAQUINA?
##############################################################################

host_footprint:
  installed:
    - CRC (OpenShift Local)
    - oc CLI (incluido con CRC)
  accounts:
    - Red Hat Account (gratuita, para pull secret)
  NOT_installed:
    - Docker
    - Podman
    - Java / JDK
    - Node.js
    - Maven
    - Kafka tools
    - Bases de datos
    - Vagrant (ya no se usa, migrado a CRC)
    - libvirt / KVM (CRC lo gestiona internamente)
    - "Nada mas"

acceptance_criteria:
  - "crc start" desde cero crea el cluster OpenShift local
  - "./deploy-all.sh" despliega los 12 servicios en dos namespaces
  - Todos los pods pasan a estado Ready en menos de 5 minutos (post-build)
  - Los operadores (Strimzi, AMQ Broker, Apicurio) se instalan automaticamente
  - Todas las Routes son accesibles desde el host via *.apps-crc.testing
  - "oc start-build" reconstruye imagenes desde el codigo fuente local
  - "crc stop && crc start" reinicia el cluster y los servicios se recuperan
  - "oc delete project" + "./deploy-all.sh" recrea todo desde cero
  - La consola web de OpenShift es accesible y muestra todos los recursos
