# =============================================================================
# Guidewire Integration POC — Full Service Stack
# =============================================================================
# Usage:
#   podman-compose up -d              # Start all services
#   podman-compose down               # Stop all services (data persists)
#   podman-compose logs -f [service]  # View logs
#   podman-compose ps                 # Check status
# =============================================================================

version: "3.9"

networks:
  guidewire-net:
    driver: bridge

volumes:
  pgdata:
  kafka-data:
  artemis-data:

services:

  # ===========================================================================
  # Phase 1: Data & Messaging
  # ===========================================================================

  # --- PostgreSQL 16 ---------------------------------------------------------
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: gw-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro,Z
    networks:
      - guidewire-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # --- Apache Kafka 3.7 (KRaft mode) ----------------------------------------
  kafka:
    image: ${KAFKA_IMAGE}
    container_name: gw-kafka
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@localhost:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - guidewire-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # --- ActiveMQ Artemis 2.33 -------------------------------------------------
  activemq:
    image: ${ACTIVEMQ_IMAGE}
    container_name: gw-activemq
    environment:
      ARTEMIS_USER: ${ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${ARTEMIS_PASSWORD}
    ports:
      - "${ARTEMIS_AMQP_PORT}:61616"
      - "${ARTEMIS_CONSOLE_PORT}:8161"
    volumes:
      - artemis-data:/var/lib/artemis-instance/data
    networks:
      - guidewire-net
    healthcheck:
      test: ["CMD-SHELL", "/var/lib/artemis-instance/bin/artemis check node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # ===========================================================================
  # Phase 2: Platform & Tools
  # ===========================================================================

  # --- Kafdrop 4.0 (Kafka UI) -----------------------------------------------
  kafdrop:
    image: ${KAFDROP_IMAGE}
    container_name: gw-kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx128M"
    ports:
      - "${KAFDROP_PORT}:9000"
    networks:
      - guidewire-net
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  # --- Apicurio Registry 2.5 ------------------------------------------------
  apicurio:
    image: ${APICURIO_IMAGE}
    container_name: gw-apicurio
    environment:
      REGISTRY_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${APICURIO_DB_NAME}
      REGISTRY_DATASOURCE_USERNAME: ${APICURIO_DB_USER}
      REGISTRY_DATASOURCE_PASSWORD: ${APICURIO_DB_PASSWORD}
    ports:
      - "${APICURIO_PORT}:8080"
    networks:
      - guidewire-net
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  # --- 3Scale APIcast (standalone gateway) -----------------------------------
  apicast:
    image: ${APICAST_IMAGE}
    container_name: gw-apicast
    environment:
      THREESCALE_CONFIG_FILE: /config/apicast-config.json
      APICAST_LOG_LEVEL: info
    ports:
      - "${APICAST_PROXY_PORT}:8080"
      - "${APICAST_MGMT_PORT}:8090"
    volumes:
      - ./config/apicast-config.json:/config/apicast-config.json:ro,Z
    networks:
      - guidewire-net
    restart: unless-stopped

  # ===========================================================================
  # Phase 3: Integration Engines
  # ===========================================================================

  # --- Drools KIE Engine ----------------------------------------------------
  drools-engine:
    image: localhost/guidewire-poc/drools-engine:latest
    build:
      context: ../../components/drools-engine
    container_name: gw-drools-engine
    ports:
      - "${DROOLS_ENGINE_PORT}:8086"
    networks:
      - guidewire-net
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # --- Apache Camel Gateway --------------------------------------------------
  camel-gateway:
    image: localhost/guidewire-poc/camel-gateway:latest
    build:
      context: ../../components/camel-gateway
    container_name: gw-camel-gateway
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APICURIO_URL: http://apicurio:8080/apis/registry/v2
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: ${ARTEMIS_USER}
      ACTIVEMQ_PASSWORD: ${ARTEMIS_PASSWORD}
    ports:
      - "${CAMEL_GATEWAY_PORT}:8083"
    networks:
      - guidewire-net
    depends_on:
      kafka:
        condition: service_healthy
      apicurio:
        condition: service_healthy
      activemq:
        condition: service_healthy
    restart: unless-stopped

  # ===========================================================================
  # Phase 4: Business Microservices
  # ===========================================================================

  # --- Billing Service -------------------------------------------------------
  billing-service:
    image: localhost/guidewire-poc/billing-service:latest
    build:
      context: ../../components/billing-service
    container_name: gw-billing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/billing
      SPRING_DATASOURCE_USERNAME: ${BILLING_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${BILLING_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APICURIO_URL: http://apicurio:8080/apis/registry/v2
    ports:
      - "${BILLING_SERVICE_PORT}:8082"
    networks:
      - guidewire-net
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

  # --- Incidents Service -----------------------------------------------------
  incidents-service:
    image: localhost/guidewire-poc/incidents-service:latest
    build:
      context: ../../components/incidents-service
    container_name: gw-incidents-service
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/incidents
      QUARKUS_DATASOURCE_USERNAME: ${INCIDENTS_DB_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${INCIDENTS_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APICURIO_URL: http://apicurio:8080/apis/registry/v2
    ports:
      - "${INCIDENTS_SERVICE_PORT}:8084"
    networks:
      - guidewire-net
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

  # --- Customers Service -----------------------------------------------------
  customers-service:
    image: localhost/guidewire-poc/customers-service:latest
    build:
      context: ../../components/customers-service
    container_name: gw-customers-service
    environment:
      DATABASE_URL: postgresql://${CUSTOMERS_DB_USER}:${CUSTOMERS_DB_PASSWORD}@postgres:5432/customers
      KAFKA_BROKERS: kafka:9092
      APICURIO_URL: http://apicurio:8080/apis/registry/v2
    ports:
      - "${CUSTOMERS_SERVICE_PORT}:8085"
    networks:
      - guidewire-net
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
