---
# Option 1: ApicurioRegistry CRD (requires Apicurio Registry Operator)
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio-registry
  namespace: guidewire-infra
  labels:
    app.kubernetes.io/part-of: guidewire-poc
spec:
  configuration:
    persistence: sql
    sql:
      dataSource:
        url: jdbc:postgresql://postgres.guidewire-infra.svc.cluster.local:5432/apicurio
        userName: apicurio
        password: apicurio123
  deployment:
    replicas: 1
---
# Option 2: Fallback Deployment (if operator is not installed)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: guidewire-infra
  labels:
    app: apicurio-registry
    app.kubernetes.io/part-of: guidewire-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
        app.kubernetes.io/part-of: guidewire-poc
    spec:
      containers:
        - name: apicurio-registry
          image: quay.io/apicurio/apicurio-registry-sql:2.5.11.Final
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REGISTRY_DATASOURCE_URL
              value: jdbc:postgresql://postgres.guidewire-infra.svc.cluster.local:5432/apicurio
            - name: REGISTRY_DATASOURCE_USERNAME
              value: apicurio
            - name: REGISTRY_DATASOURCE_PASSWORD
              value: apicurio123
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
  namespace: guidewire-infra
  labels:
    app: apicurio-registry
    app.kubernetes.io/part-of: guidewire-poc
spec:
  selector:
    app: apicurio-registry
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
