---
# Apicurio Registry 3.1.7 — Backend API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: guidewire-infra
  labels:
    app: apicurio-registry
    app.kubernetes.io/part-of: guidewire-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
        app.kubernetes.io/part-of: guidewire-poc
    spec:
      containers:
        - name: apicurio-registry
          image: docker.io/apicurio/apicurio-registry:3.1.7
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APICURIO_STORAGE_KIND
              value: sql
            - name: APICURIO_STORAGE_SQL_KIND
              value: postgresql
            - name: APICURIO_DATASOURCE_URL
              value: jdbc:postgresql://postgres.guidewire-infra.svc.cluster.local:5432/apicurio
            - name: APICURIO_DATASOURCE_USERNAME
              value: apicurio
            - name: APICURIO_DATASOURCE_PASSWORD
              value: apicurio123
            # Enable content mutability for Draft artifacts (Apicurio Studio feature)
            - name: APICURIO_REST_MUTABILITY_ARTIFACT__VERSION__CONTENT_ENABLED
              value: "true"
            # CORS — allow UI and external access
            - name: APICURIO_CORS_ALLOWED_ORIGINS
              value: "*"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
  namespace: guidewire-infra
  labels:
    app: apicurio-registry
    app.kubernetes.io/part-of: guidewire-poc
spec:
  selector:
    app: apicurio-registry
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
---
# Apicurio Registry 3.1.7 — UI (separate container in v3)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-ui
  namespace: guidewire-infra
  labels:
    app: apicurio-registry-ui
    app.kubernetes.io/part-of: guidewire-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry-ui
  template:
    metadata:
      labels:
        app: apicurio-registry-ui
        app.kubernetes.io/part-of: guidewire-poc
    spec:
      containers:
        - name: apicurio-registry-ui
          image: docker.io/apicurio/apicurio-registry-ui:3.1.7
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REGISTRY_API_URL
              value: http://apicurio-registry:8080/apis/registry/v3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry-ui
  namespace: guidewire-infra
  labels:
    app: apicurio-registry-ui
    app.kubernetes.io/part-of: guidewire-poc
spec:
  selector:
    app: apicurio-registry-ui
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
